services:
  bayrol-bridge:
    image: git.zk35.de/secalpha/bayrol-bridge:latest
    ports:
      - "8883:8883"
    volumes:
      - ./config.yaml:/config.yaml:ro
      - certs:/mosquitto/certs
    restart: unless-stopped

volumes:
  certs:
